[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[build.nixpacks]
phases.setup.nixPkgs = ["nodejs-20_x", "npm-10_x"]
phases.install.cmds = ["cd backend && npm install"]
phases.build.cmds = ["cd backend && npm run build:prod"]
